apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp2
  labels:
    app: web2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web2
  template:
    metadata:
      labels:
        app: web2
        access: accepted
    spec:
      containers:
      - name: webapp2
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp2-service
spec:
  type: ClusterIP
  selector:
    app: web2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80