apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
  - name: c1
    image: busybox:1.31.1
    args: [/bin/sh, -c, "while true; do echo $(hostname) $(date) >> /var/log/date.log; sleep 5; done"]
    volumeMounts:
    - name: datelog
      mountPath: /var/log
  - name: c2
    image: busybox:1.31.1
    volumeMounts:
    - name: datelog
      mountPath: /usr/share/
    args: [/bin/sh, -c, "tail -f /usr/share/date.log"]
  volumes:
  - name: datelog 
    emptyDir: {}